### ISSUE TITLE
Growing of TCP connection

### ISSUE THREAD

**Issue by cesco69** [danieleteti/delphiredisclient#29]
Hi Daniele,

I'm using delphiredisclient (master) on a `TWebModule`.

on WebModule creation I create a new `TIdTCPClient` and connect to Redis, e.g.:

```pascal
procedure TWebService.WebModuleCreate(Sender: TObject);-
begin
    FClient := TIdTCPClient.Create();
    FClient.Connect('REDIS_HOST', 6379);
end;
```

and on web module destroy, I disconnect and free the resource, e.g.:

```pascal
procedure TWebService.WebModuleDestroy(Sender: TObject);
begin
    FClient.Disconnect;
    FClient.Free;
end;
```

All works... But this way I create a new connection on every new request and after a lot of time there is a growing number of `TIME_WAIT` sockets.

```shell
netstat -na | find "6379"
```

![image](https://user-images.githubusercontent.com/6096678/117006575-e89e2300-ace8-11eb-9a14-a0a65a11a9a3.png)

I would like to implement a global connection pool.

Has delphiredisclient something to manage a pool of TCP connections?

**Comment by danieleteti** [comment]
WebModules are recycled by WebBroker. The pool must be handled outside of the http request.

**Comment by cesco69** [comment]
Yes @danieleteti I'm writing an connection pool for Redis Client https://codereview.stackexchange.com/questions/260418/delphi-tidtcpclient-connection-pool-in-a-multithread-environment take a look, maybe it can be a part of this project

**Comment by danieleteti** [comment]
Interesting. Would you like to contribute to the project?
