### ISSUE TITLE
python build script not working (enhancement)

### ISSUE THREAD

**Issue by Basti-Fantasti** [danieleteti/delphiredisclient#30]
Hi,

I just tried to install / setup the delphiredisclient and found out that additional python packages are needed for the installer to run.
Maybe you can add a requirements.txt so that it's possible to easily setup a venv for the installation process.

**Comment by Zhou171542036** [comment]
来信已收到。

**Comment by danieleteti** [comment]
There no installer. Just put units in your Delphi lib path.
