### ISSUE TITLE
Building not possible because of missing settings and dependencies

### ISSUE THREAD

**Issue by Basti-Fantasti** [danieleteti/delphiredisclient#31]
Hi,

I've tried to install the delphiredisclient.
When running the build.py script, it throws a lot of erros because of missing settings which are not mentioned

- LoggerPro needs to be setup prior to setting up the redis client
- the redisclient/source dir needs to be added to the delphi library path. Otherwise some builds fail

**Comment by danieleteti** [comment]
The build script is not related to the Delphi installation. It is required just to rebuild all unit test, run them, and build all the samples

**Comment by Basti-Fantasti** [comment]
ok that's good to know 😄 
so for the `installation` it's sufficient to just add the sources subfolder to the library path (as with the LoggerPro components)

**Comment by danieleteti** [comment]
Yes, just the units path in the Delphi library paths :-)
