### ISSUE TITLE
Callback SUBSCRIBE Exception.

### ISSUE THREAD

**Issue by fredycc** [danieleteti/delphiredisclient#4]
Hi, I have a problem when read callback message on SUSCRIBE method. In this validation:

`if (not FValidResponse) or (lArrNull.Items[0] <> 'message') then
        raise ERedisException.CreateFmt('Invalid reply: %s',
          [string.Join('-', lArrNull.ToArray)]);
`

After remove (not FValidResponse) all is working.

`if (lArrNull.Items[0] <> 'message') then
        raise ERedisException.CreateFmt('Invalid reply: %s',
          [string.Join('-', lArrNull.ToArray)]);
`

I'm using redis for windows https://github.com/MSOpenTech/redis/releases
Delphi Berlin Upd 2

Regards

**Comment by danieleteti** [comment]
FIXED in the last push. There is also an additional callback (optional) to the SUBSCRIBE call, in case you need to know when precisely the subscription is happening.
